[Variables]
; if set to 1, all hour markers except the ones directly before and after the needle will be hidden
UltraMinimalism = 1
; if set to 1, the current hour and minute will be displayed in the center when the mouse is hovered over the clock
ShowTimeOnHover = 1

Size = 200

NeedleColor = 255,255,255,255
LineColor = 255,255,255,255
BackgroundColor = 0,0,0,1

NeedleLength = 30
NeedleWidth = 2

LineWidth = 4
LineLength = 20
; the size multiplier for hour markers that aren't 12, 3, 6, or 9
SmallLineRatio = 0.65
